server:
  port: 9000
  error:
    include-message: always
logging:
  level:
    org.springframework.security: trace
spring:
  application:
    name: demo-app
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2_demo
    username: student_admin
    password: $tuD3nt
  jdbc:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  security:
    user:
      name: user1
      password: password
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
# Actuator
management:
  endpoints:
    web:
      exposure.include=*
  health:
    show-details: always
  info:
    env:
      enabled=true