server:
  port: 9443
  ssl:
    bundle: oauth2-server
    client-auth: want
  error:
    include-message: always
spring:
  application:
    name: oauth2-server
  datasource:
    initialize: true
    schema: schema-postgresql.sql
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/oauth2_demo
    username: student_admin
    password: $tuD3nt
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always
  ssl:
    bundle:
      jks:
        oauth2-server:
          key:
            alias: oauth2-server-certificate
            password: changeit
          keystore:
            location: classpath:keystore.p12
            password: changeit
            type: PKCS12
          truststore:
            location: classpath:truststore
            password: changeit
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
# Actuator
management:
  endpoints:
    web:
      exposure.include=*
  health:
    show-details: always
  info:
    env:
      enabled=true